#!/bin/bash

container_id=$(docker ps --format "table {{.ID}}\t{{.Names}}" \
    | grep -i 'ofxparser_php_' \
    | cut -d " " -f 1)

docker exec -it $container_id sh -c "cd /www/ofxparser && ./vendor/bin/phpunit $*"
